export const MASTER_DATA = {
  hiragana: [
    { char: "あ", romaji: "a", mnemonic: "Looks like an 'Apple' with a stem." },
    { char: "い", romaji: "i", mnemonic: "Two 'i's standing side by side." },
    { char: "う", romaji: "u", mnemonic: "Side profile of someone saying 'Ugh!'" },
    { char: "え", romaji: "e", mnemonic: "An 'Exotic' bird on a branch." },
    { char: "お", romaji: "o", mnemonic: "A golfer hitting a ball 'On'to the green." },
    { char: "か", romaji: "ka", mnemonic: "A 'Ka'yak paddle hitting the water." },
    { char: "き", romaji: "ki", mnemonic: "It looks just like a 'Key'." },
    { char: "く", romaji: "ku", mnemonic: "The open beak of a 'Cu'ckoo bird." },
    { char: "け", romaji: "ke", mnemonic: "A 'Ke'g of cider." },
    { char: "こ", romaji: "ko", mnemonic: "Two 'Co'habitating worms." },
    { char: "さ", romaji: "sa", mnemonic: "A 'Sa'iling boat on the sea." },
    { char: "し", romaji: "shi", mnemonic: "A 'She'll' (hook) for fishing." },
    { char: "す", romaji: "su", mnemonic: "A 'Su'per swing set." },
    { char: "せ", romaji: "se", mnemonic: "Two people 'Se'tting' on a bench." },
    { char: "そ", romaji: "so", mnemonic: "A 'So'ngbird on a perch." },
    { char: "た", romaji: "ta", mnemonic: "The letters 't' and 'a' combined." },
    { char: "ち", romaji: "chi", mnemonic: "A 'Chee'rleader waving pom-poms." },
    { char: "つ", romaji: "tsu", mnemonic: "A big 'Tsu'nami wave." },
    { char: "て", romaji: "te", mnemonic: "A 'Te'n' (10) tilted over." },
    { char: "と", romaji: "to", mnemonic: "A 'To'e with a splinter in it." },
    { char: "な", romaji: "na", mnemonic: "A 'Nu'n praying in front of a cross." },
    { char: "に", romaji: "ni", mnemonic: "A 'Knee' with a bandage on it." },
    { char: "ぬ", romaji: "nu", mnemonic: "A plate of 'Noo'dles with chopsticks." },
    { char: "ね", romaji: "ne", mnemonic: "A 'Ne'lly' (cat) with a curly tail." },
    { char: "の", romaji: "no", mnemonic: "A 'No' entry sign." },
    { char: "は", romaji: "ha", mnemonic: "A 'Ha'ha! (funny) person laughing." },
    { char: "ひ", romaji: "hi", mnemonic: "A big 'Hi'p smile." },
    { char: "ふ", romaji: "fu", mnemonic: "Mount 'Fu'ji's snowy peak." },
    { char: "へ", romaji: "he", mnemonic: "A 'He'll' (hill) to climb." },
    { char: "ほ", romaji: "ho", mnemonic: "A 'Ho't' stove with a flame." },
    { char: "ま", romaji: "ma", mnemonic: "A 'Ma'st' on a ship." },
    { char: "み", romaji: "mi", mnemonic: "Who is 21? 'Me'!" },
    { char: "む", romaji: "mu", mnemonic: "A 'Moo'ing cow." },
    { char: "め", romaji: "me", mnemonic: "A 'Me'ssy' plate of noodles." },
    { char: "も", romaji: "mo", mnemonic: "A 'Mo're' (more) fish on a hook." },
    { char: "や", romaji: "ya", mnemonic: "A 'Ya'cht' on the water." },
    { char: "ゆ", romaji: "yu", mnemonic: "A 'U'-turn symbol." },
    { char: "よ", romaji: "yo", mnemonic: "A 'Yo'-yo on a string." },
    { char: "ら", romaji: "ra", mnemonic: "A 'Ra'bbit' sitting down." },
    { char: "り", romaji: "ri", mnemonic: "Two stalks of 'Ree'ds." },
    { char: "る", romaji: "ru", mnemonic: "A 'Rou'te' with a loop-de-loop." },
    { char: "れ", romaji: "re", mnemonic: "A person 'Re'aching' for something." },
    { char: "ろ", romaji: "ro", mnemonic: "A 'Ro'ad' with no end." },
    { char: "わ", romaji: "wa", mnemonic: "A 'Wa'sp' flying by." },
    { char: "を", romaji: "wo", mnemonic: "Someone 'Wo'lking' on a tightrope." },
    { char: "ん", romaji: "n", mnemonic: "The letter 'n' cursive." }
  ],
  katakana: [
    { char: "ア", romaji: "a", mnemonic: "An 'A'ngle of a cliff." },
    { char: "イ", romaji: "i", mnemonic: "An 'Ea'sel for painting." },
    { char: "ウ", romaji: "u", mnemonic: "A cook's cap (U is for 'U'tensils)." },
    { char: "エ", romaji: "e", mnemonic: "The girders of an 'En'gineer's bridge." },
    { char: "オ", romaji: "o", mnemonic: "An 'O'pera singer." },
    { char: "カ", romaji: "ka", mnemonic: "Sharp 'ka'yak paddle." },
    { char: "キ", romaji: "ki", mnemonic: "A sharp 'ki' (key)." },
    { char: "ク", romaji: "ku", mnemonic: "A 'Co'ok's knife." },
    { char: "ケ", romaji: "ke", mnemonic: "A 'Ke'yboard corner." },
    { char: "コ", romaji: "ko", mnemonic: "A 'Co'rner' of a box." },
    { char: "サ", romaji: "sa", mnemonic: "Three 'Sa'rdines' in a can." },
    { char: "シ", romaji: "shi", mnemonic: "A 'She' (girl) with long eyelashes." },
    { char: "ス", romaji: "su", mnemonic: "A 'Su'per' hanger." },
    { char: "セ", romaji: "se", mnemonic: "A 'Se'tting sun over a bench." },
    { char: "ソ", romaji: "so", mnemonic: "A 'So'ft' needle pointing down." },
    { char: "タ", romaji: "ta", mnemonic: "A 'Ta'dal' wave." },
    { char: "チ", romaji: "chi", mnemonic: "A 'Chee'rleader' (like a 4)." },
    { char: "ツ", romaji: "tsu", mnemonic: "Two 'Tsu'nami' waves." },
    { char: "テ", romaji: "te", mnemonic: "A 'Te'levision' antenna." },
    { char: "ト", romaji: "to", mnemonic: "A 'To'tem' pole." },
    { char: "ナ", romaji: "na", mnemonic: "A 'Na'rrow' cross." },
    { char: "ニ", romaji: "ni", mnemonic: "Two 'Ni'ckels' (2 lines)." },
    { char: "ヌ", romaji: "nu", mnemonic: "A 'Noo'dle' chopstick." },
    { char: "ネ", romaji: "ne", mnemonic: "A 'Ne'cktie'." },
    { char: "ノ", romaji: "no", mnemonic: "A 'No'se' bridge." },
    { char: "ハ", romaji: "ha", mnemonic: "A 'Ha't' (the top)." },
    { char: "ヒ", romaji: "hi", mnemonic: "A 'Hee'-haw'ing donkey." },
    { char: "フ", romaji: "fu", mnemonic: "A 'Fu'nny' flag." },
    { char: "ヘ", romaji: "he", mnemonic: "A 'He'll' (hill)." },
    { char: "ホ", romaji: "ho", mnemonic: "A 'Ho'ly' cross." },
    { char: "マ", romaji: "ma", mnemonic: "A 'Ma'ma's' lap." },
    { char: "ミ", romaji: "mi", mnemonic: "Three 'Mi'ssiles'." },
    { char: "ム", romaji: "mu", mnemonic: "A 'Mo'o'ing cow face." },
    { char: "メ", romaji: "me", mnemonic: "A 'Me'tal' sword (X)." },
    { char: "モ", romaji: "mo", mnemonic: "Sharp Hiragana 'mo'." },
    { char: "ヤ", romaji: "ya", mnemonic: "Sharp Hiragana 'ya'." },
    { char: "ユ", romaji: "yu", mnemonic: "A 'U'nit' of shelves." },
    { char: "ヨ", romaji: "yo", mnemonic: "A 'Yo'ga' mat folded." },
    { char: "ラ", romaji: "ra", mnemonic: "A 'Ra'dio' with a handle." },
    { char: "リ", romaji: "ri", mnemonic: "Two stalks of 'Ree'ds." },
    { char: "ル", romaji: "ru", mnemonic: "Two 'Roo'ts' of a tree." },
    { char: "レ", romaji: "re", mnemonic: "A 'Re'd' flag blowing." },
    { char: "ロ", romaji: "ro", mnemonic: "A 'Ro'ad' block (square)." },
    { char: "ワ", romaji: "wa", mnemonic: "A 'Wa'ter' tap." },
    { char: "ヲ", romaji: "wo", mnemonic: "A 'Wo'lker' (walker) with a cane." },
    { char: "ン", romaji: "n", mnemonic: "One eye 'n' a smile." }
  ],
kanji: [
  { char: "一", romaji: "ichi", meaning: "One", mnemonic: "One horizontal stroke." },
    { char: "二", romaji: "ni", meaning: "Two", mnemonic: "Two horizontal strokes." },
    { char: "三", romaji: "san", meaning: "Three", mnemonic: "Three horizontal strokes." },
    { char: "日", romaji: "hi", meaning: "Sun / Day", mnemonic: "A window looking out at the sun." },
    { char: "本", romaji: "hon", meaning: "Book / Origin", mnemonic: "A tree with a mark showing the roots." },
    { char: "人", romaji: "hito", meaning: "Person", mnemonic: "A person walking on two legs." },
    { char: "月", romaji: "tsuki", meaning: "Moon / Month", mnemonic: "A crescent moon with clouds." },
    { char: "火", romaji: "hi", meaning: "Fire", mnemonic: "A campfire with sparks jumping up." },
    { char: "水", romaji: "mizu", meaning: "Water", mnemonic: "A splashing stream of water." },
    { char: "木", romaji: "ki", meaning: "Tree", mnemonic: "A tree with branches and roots." }
]
};