export const MASTER_DATA = {
  hiragana: [
    { char: "あ", romaji: "a", mnemonic: "Looks like an 'Apple' with a stem." },
    { char: "い", romaji: "i", mnemonic: "Two 'i's standing side by side." },
    { char: "う", romaji: "u", mnemonic: "Side profile of someone saying 'Ugh!'" },
    { char: "え", romaji: "e", mnemonic: "An 'Exotic' bird on a branch." },
    { char: "お", romaji: "o", mnemonic: "A golfer hitting a ball 'On'to the green." },
    { char: "か", romaji: "ka", mnemonic: "A 'Ka'yak paddle hitting the water." },
    { char: "き", romaji: "ki", mnemonic: "It looks just like a 'Key'." },
    { char: "く", romaji: "ku", mnemonic: "The open beak of a 'Cu'ckoo bird." },
    { char: "け", romaji: "ke", mnemonic: "A 'Ke'g of cider." },
    { char: "こ", romaji: "ko", mnemonic: "Two 'Co'habitating worms." },
    { char: "さ", romaji: "sa", mnemonic: "A 'Sa'iling boat on the sea." },
    { char: "し", romaji: "shi", mnemonic: "A 'She'll' (hook) for fishing." },
    { char: "す", romaji: "su", mnemonic: "A 'Su'per swing set." },
    { char: "せ", romaji: "se", mnemonic: "Two people 'Se'tting' on a bench." },
    { char: "そ", romaji: "so", mnemonic: "A 'So'ngbird on a perch." },
    { char: "た", romaji: "ta", mnemonic: "The letters 't' and 'a' combined." },
    { char: "ち", romaji: "chi", mnemonic: "A 'Chee'rleader waving pom-poms." },
    { char: "つ", romaji: "tsu", mnemonic: "A big 'Tsu'nami wave." },
    { char: "て", romaji: "te", mnemonic: "A 'Te'n' (10) tilted over." },
    { char: "と", romaji: "to", mnemonic: "A 'To'e with a splinter in it." },
    { char: "な", romaji: "na", mnemonic: "A 'Nu'n praying in front of a cross." },
    { char: "に", romaji: "ni", mnemonic: "A 'Knee' with a bandage on it." },
    { char: "ぬ", romaji: "nu", mnemonic: "A plate of 'Noo'dles with chopsticks." },
    { char: "ね", romaji: "ne", mnemonic: "A 'Ne'lly' (cat) with a curly tail." },
    { char: "の", romaji: "no", mnemonic: "A 'No' entry sign." },
    { char: "は", romaji: "ha", mnemonic: "A 'Ha'ha! (funny) person laughing." },
    { char: "ひ", romaji: "hi", mnemonic: "A big 'Hi'p smile." },
    { char: "ふ", romaji: "fu", mnemonic: "Mount 'Fu'ji's snowy peak." },
    { char: "へ", romaji: "he", mnemonic: "A 'He'll' (hill) to climb." },
    { char: "ほ", romaji: "ho", mnemonic: "A 'Ho't' stove with a flame." },
    { char: "ま", romaji: "ma", mnemonic: "A 'Ma'st' on a ship." },
    { char: "み", romaji: "mi", mnemonic: "Who is 21? 'Me'!" },
    { char: "む", romaji: "mu", mnemonic: "A 'Moo'ing cow." },
    { char: "め", romaji: "me", mnemonic: "A 'Me'ssy' plate of noodles." },
    { char: "も", romaji: "mo", mnemonic: "A 'Mo're' (more) fish on a hook." },
    { char: "や", romaji: "ya", mnemonic: "A 'Ya'cht' on the water." },
    { char: "ゆ", romaji: "yu", mnemonic: "A 'U'-turn symbol." },
    { char: "よ", romaji: "yo", mnemonic: "A 'Yo'-yo on a string." },
    { char: "ら", romaji: "ra", mnemonic: "A 'Ra'bbit' sitting down." },
    { char: "り", romaji: "ri", mnemonic: "Two stalks of 'Ree'ds." },
    { char: "る", romaji: "ru", mnemonic: "A 'Rou'te' with a loop-de-loop." },
    { char: "れ", romaji: "re", mnemonic: "A person 'Re'aching' for something." },
    { char: "ろ", romaji: "ro", mnemonic: "A 'Ro'ad' with no end." },
    { char: "わ", romaji: "wa", mnemonic: "A 'Wa'sp' flying by." },
    { char: "を", romaji: "wo", mnemonic: "Someone 'Wo'lking' on a tightrope." },
    { char: "ん", romaji: "n", mnemonic: "The letter 'n' cursive." }
  ],
  katakana: [
    { char: "ア", romaji: "a", mnemonic: "An 'A'ngle of a cliff." },
    { char: "イ", romaji: "i", mnemonic: "An 'Ea'sel for painting." },
    { char: "ウ", romaji: "u", mnemonic: "A cook's cap (U is for 'U'tensils)." },
    { char: "エ", romaji: "e", mnemonic: "The girders of an 'En'gineer's bridge." },
    { char: "オ", romaji: "o", mnemonic: "An 'O'pera singer." },
    { char: "カ", romaji: "ka", mnemonic: "Sharp 'ka'yak paddle." },
    { char: "キ", romaji: "ki", mnemonic: "A sharp 'ki' (key)." },
    { char: "ク", romaji: "ku", mnemonic: "A 'Co'ok's knife." },
    { char: "ケ", romaji: "ke", mnemonic: "A 'Ke'yboard corner." },
    { char: "コ", romaji: "ko", mnemonic: "A 'Co'rner' of a box." },
    { char: "サ", romaji: "sa", mnemonic: "Three 'Sa'rdines' in a can." },
    { char: "シ", romaji: "shi", mnemonic: "A 'She' (girl) with long eyelashes." },
    { char: "ス", romaji: "su", mnemonic: "A 'Su'per' hanger." },
    { char: "セ", romaji: "se", mnemonic: "A 'Se'tting sun over a bench." },
    { char: "ソ", romaji: "so", mnemonic: "A 'So'ft' needle pointing down." },
    { char: "タ", romaji: "ta", mnemonic: "A 'Ta'dal' wave." },
    { char: "チ", romaji: "chi", mnemonic: "A 'Chee'rleader' (like a 4)." },
    { char: "ツ", romaji: "tsu", mnemonic: "Two 'Tsu'nami' waves." },
    { char: "テ", romaji: "te", mnemonic: "A 'Te'levision' antenna." },
    { char: "ト", romaji: "to", mnemonic: "A 'To'tem' pole." },
    { char: "ナ", romaji: "na", mnemonic: "A 'Na'rrow' cross." },
    { char: "ニ", romaji: "ni", mnemonic: "Two 'Ni'ckels' (2 lines)." },
    { char: "ヌ", romaji: "nu", mnemonic: "A 'Noo'dle' chopstick." },
    { char: "ネ", romaji: "ne", mnemonic: "A 'Ne'cktie'." },
    { char: "ノ", romaji: "no", mnemonic: "A 'No'se' bridge." },
    { char: "ハ", romaji: "ha", mnemonic: "A 'Ha't' (the top)." },
    { char: "ヒ", romaji: "hi", mnemonic: "A 'Hee'-haw'ing donkey." },
    { char: "フ", romaji: "fu", mnemonic: "A 'Fu'nny' flag." },
    { char: "ヘ", romaji: "he", mnemonic: "A 'He'll' (hill)." },
    { char: "ホ", romaji: "ho", mnemonic: "A 'Ho'ly' cross." },
    { char: "マ", romaji: "ma", mnemonic: "A 'Ma'ma's' lap." },
    { char: "ミ", romaji: "mi", mnemonic: "Three 'Mi'ssiles'." },
    { char: "ム", romaji: "mu", mnemonic: "A 'Mo'o'ing cow face." },
    { char: "メ", romaji: "me", mnemonic: "A 'Me'tal' sword (X)." },
    { char: "モ", romaji: "mo", mnemonic: "Sharp Hiragana 'mo'." },
    { char: "ヤ", romaji: "ya", mnemonic: "Sharp Hiragana 'ya'." },
    { char: "ユ", romaji: "yu", mnemonic: "A 'U'nit' of shelves." },
    { char: "ヨ", romaji: "yo", mnemonic: "A 'Yo'ga' mat folded." },
    { char: "ラ", romaji: "ra", mnemonic: "A 'Ra'dio' with a handle." },
    { char: "リ", romaji: "ri", mnemonic: "Two stalks of 'Ree'ds." },
    { char: "ル", romaji: "ru", mnemonic: "Two 'Roo'ts' of a tree." },
    { char: "レ", romaji: "re", mnemonic: "A 'Re'd' flag blowing." },
    { char: "ロ", romaji: "ro", mnemonic: "A 'Ro'ad' block (square)." },
    { char: "ワ", romaji: "wa", mnemonic: "A 'Wa'ter' tap." },
    { char: "ヲ", romaji: "wo", mnemonic: "A 'Wo'lker' (walker) with a cane." },
    { char: "ン", romaji: "n", mnemonic: "One eye 'n' a smile." }
  ],
  kanji: {
    n5: [
  // --- NUMBERS (14) ---
  { char: "一", romaji: "ichi", meaning: "One", category: "Numbers", mnemonic: "One line." },
{ char: "日", romaji: "hi", meaning: "Sun", category: "Time", mnemonic: "Window to the sun." },
{ char: "人", romaji: "hito", meaning: "Person", category: "People", mnemonic: "A person walking." },
  { char: "一", romaji: "ichi", meaning: "One", mnemonic: "One horizontal line." },
  { char: "二", romaji: "ni", meaning: "Two", mnemonic: "Two horizontal lines." },
  { char: "三", romaji: "san", meaning: "Three", mnemonic: "Three horizontal lines." },
  { char: "四", romaji: "yon", meaning: "Four", mnemonic: "Four legs inside a mouth (box)." },
  { char: "五", romaji: "go", meaning: "Five", mnemonic: "A stylized number 5." },
  { char: "六", romaji: "roku", meaning: "Six", mnemonic: "A person wearing a hat." },
  { char: "七", romaji: "nana", meaning: "Seven", mnemonic: "An upside-down 7." },
  { char: "八", romaji: "hachi", meaning: "Eight", mnemonic: "A mountain opening up." },
  { char: "九", romaji: "kyuu", meaning: "Nine", mnemonic: "A person being kicked (9 times)." },
  { char: "十", romaji: "juu", meaning: "Ten", mnemonic: "A perfect cross." },
  { char: "百", romaji: "hyaku", meaning: "Hundred", mnemonic: "One hundred (Looks like a white stone)." },
  { char: "千", romaji: "sen", meaning: "Thousand", mnemonic: "A person with a horizontal line." },
  { char: "万", romaji: "man", meaning: "Ten Thousand", mnemonic: "Ten thousand (Looks like a bird)." },
  { char: "円", romaji: "en", meaning: "Yen/Circle", mnemonic: "A coin inside a box." },

  // --- TIME & CALENDAR (15) ---
  { char: "日", romaji: "hi", meaning: "Sun/Day", mnemonic: "Window to the sun." },
  { char: "月", romaji: "tsuki", meaning: "Moon/Month", mnemonic: "A crescent moon." },
  { char: "火", romaji: "hi", meaning: "Fire", mnemonic: "A flickering flame." },
  { char: "水", romaji: "mizu", meaning: "Water", mnemonic: "A splashing stream." },
  { char: "木", romaji: "ki", meaning: "Tree", mnemonic: "Tree with branches." },
  { char: "金", romaji: "kane", meaning: "Gold/Money", mnemonic: "Gold under a roof." },
  { char: "土", romaji: "tsuchi", meaning: "Earth/Soil", mnemonic: "A sprout in the soil." },
  { char: "年", romaji: "toshi", meaning: "Year", mnemonic: "A harvest person (Yearly)." },
  { char: "時", romaji: "toki", mnemonic: "Time/Hour", meaning: "Sun and temple together." },
  { char: "分", romaji: "fun", meaning: "Minute/Divide", mnemonic: "A knife dividing things." },
  { char: "今", romaji: "ima", meaning: "Now", mnemonic: "Under the roof right now." },
  { char: "先", romaji: "saki", meaning: "Previous", mnemonic: "Walking ahead of others." },
  { char: "来", romaji: "rai", meaning: "To Come", mnemonic: "A tree with more fruit coming." },
  { char: "毎", romaji: "mai", meaning: "Every", mnemonic: "A person every day." },
  { char: "半", romaji: "han", meaning: "Half", mnemonic: "Eight cut in half." },

  // --- DIRECTIONS & PLACES (16) ---
  { char: "上", romaji: "ue", meaning: "Up", mnemonic: "Above the line." },
  { char: "下", romaji: "shita", meaning: "Down", mnemonic: "Below the line." },
  { char: "左", romaji: "hidari", meaning: "Left", mnemonic: "Hand with a tool on the left." },
  { char: "右", romaji: "migi", meaning: "Right", mnemonic: "Hand and a mouth on the right." },
  { char: "中", romaji: "naka", meaning: "Middle", mnemonic: "Line through the middle." },
  { char: "外", romaji: "soto", meaning: "Outside", mnemonic: "Evening and a moon outside." },
  { char: "前", romaji: "mae", meaning: "Before/Front", mnemonic: "Standing before a horn." },
  { char: "後", romaji: "ato", meaning: "After/Behind", mnemonic: "Someone following behind." },
  { char: "北", romaji: "kita", meaning: "North", mnemonic: "Two people back to back." },
  { char: "南", romaji: "minami", meaning: "South", mnemonic: "The warm southern roof." },
  { char: "東", romaji: "higashi", meaning: "East", mnemonic: "Sun rising in a tree." },
  { char: "西", romaji: "nishi", meaning: "West", mnemonic: "Sun setting in a bird's nest." },
  { char: "間", romaji: "aida", meaning: "Between", mnemonic: "Sun between the gates." },
  { char: "国", romaji: "kuni", meaning: "Country", mnemonic: "King in a box (borders)." },
  { char: "駅", romaji: "eki", meaning: "Station", mnemonic: "Horse at the station." },
  { char: "店", romaji: "mise", meaning: "Shop", mnemonic: "Occupying a building." },

  // --- NATURE & ELEMENTS (10) ---
  { char: "山", romaji: "yama", meaning: "Mountain", mnemonic: "Three mountain peaks." },
  { char: "川", romaji: "kawa", meaning: "River", mnemonic: "A flowing stream." },
  { char: "田", romaji: "ta", meaning: "Rice Field", mnemonic: "Four rice plots." },
  { char: "天", romaji: "ten", meaning: "Heaven/Sky", mnemonic: "Great big sky above man." },
  { char: "気", romaji: "ki", meaning: "Spirit/Energy", mnemonic: "Steam rising from rice." },
  { char: "空", romaji: "sora", meaning: "Sky/Empty", mnemonic: "A roof over a hole." },
  { char: "雨", romaji: "ame", meaning: "Rain", mnemonic: "Raindrops in a window." },
  { char: "電", romaji: "den", meaning: "Electricity", mnemonic: "Rain and lightning." },
  { char: "花", romaji: "hana", meaning: "Flower", mnemonic: "Grass that changes." },
  { char: "魚", romaji: "sakana", meaning: "Fish", mnemonic: "A fish with its tail." },

  // --- PEOPLE & BODY (12) ---
  { char: "人", romaji: "hito", meaning: "Person", mnemonic: "A person walking." },
  { char: "子", romaji: "ko", meaning: "Child", mnemonic: "A baby with arms open." },
  { char: "女", romaji: "onna", meaning: "Woman", mnemonic: "A sitting woman." },
  { char: "男", romaji: "otoko", meaning: "Man", mnemonic: "Power in the rice field." },
  { char: "父", romaji: "chichi", meaning: "Father", mnemonic: "Father's mustache." },
  { char: "母", romaji: "haha", meaning: "Mother", mnemonic: "Mother with breasts." },
  { char: "友", romaji: "tomo", meaning: "Friend", mnemonic: "Two hands joined." },
  { char: "名", romaji: "na", meaning: "Name", mnemonic: "Saying your name at night." },
  { char: "目", romaji: "me", meaning: "Eye", mnemonic: "A vertical eye." },
  { char: "耳", romaji: "mimi", meaning: "Ear", mnemonic: "A person's ear." },
  { char: "手", romaji: "te", meaning: "Hand", mnemonic: "A hand with fingers." },
  { char: "足", romaji: "ashi", meaning: "Foot", mnemonic: "A leg and a foot." },

  // --- ACTIONS & VERBS (15) ---
  { char: "行", romaji: "i(ku)", meaning: "To Go", mnemonic: "A crossroad." },
  { char: "見", romaji: "mi(ru)", meaning: "To See", mnemonic: "Eye on legs." },
  { char: "言", romaji: "i(u)", meaning: "To Say", mnemonic: "Words from a mouth." },
  { char: "語", romaji: "go", meaning: "Language", mnemonic: "Saying five words." },
  { char: "読", romaji: "yo(mu)", meaning: "To Read", mnemonic: "Words in a market." },
  { char: "書", romaji: "ka(ku)", meaning: "To Write", mnemonic: "Hand with a brush." },
  { char: "食", romaji: "ta(beru)", meaning: "To Eat", mnemonic: "Food under a roof." },
  { char: "飲", romaji: "no(mu)", meaning: "To Drink", mnemonic: "Missing food (liquid)." },
  { char: "買", romaji: "ka(u)", meaning: "To Buy", mnemonic: "Shells (money) in a net." },
  { char: "出", romaji: "de(ru)", meaning: "To Exit", mnemonic: "Mountains growing out." },
  { char: "入", romaji: "hai(ru)", meaning: "To Enter", mnemonic: "Person going inside." },
  { char: "休", romaji: "yasu(mu)", meaning: "To Rest", mnemonic: "Person by a tree." },
  { char: "聞", romaji: "ki(ku)", meaning: "To Hear", mnemonic: "Ear at the gate." },
  { char: "話", romaji: "hana(su)", meaning: "To Speak", mnemonic: "Words from a tongue." },
  { char: "生", romaji: "sei", meaning: "Life/Birth", mnemonic: "Plant growing from soil." },

  // --- DESCRIPTORS & SCHOOL (18) ---
  { char: "大", romaji: "oo(kii)", meaning: "Big", mnemonic: "Person stretching out." },
  { char: "小", romaji: "chii(sai)", meaning: "Small", mnemonic: "Small drops." },
  { char: "多", romaji: "oo(i)", meaning: "Many", mnemonic: "Two moons (Many nights)." },
  { char: "少", romaji: "suku(nai)", meaning: "Few", mnemonic: "Small with a cut." },
  { char: "高", romaji: "taka(i)", meaning: "High/Expensive", mnemonic: "A tall building." },
  { char: "安", romaji: "yasu(i)", meaning: "Cheap/Safe", mnemonic: "Woman under a roof." },
  { char: "新", romaji: "atara(shii)", meaning: "New", mnemonic: "Standing on a tree with an axe." },
  { char: "古", romaji: "furu(i)", meaning: "Old", mnemonic: "Ten mouths (Telling old stories)." },
  { char: "白", romaji: "shiro", meaning: "White", mnemonic: "A white drop of sun." },
  { char: "長", romaji: "naga(i)", meaning: "Long", mnemonic: "Leader with long hair." },
  { char: "本", romaji: "hon", meaning: "Book/Origin", mnemonic: "Root of a tree." },
  { char: "学", romaji: "gaku", meaning: "Study", mnemonic: "Child under a school roof." },
  { char: "校", romaji: "kou", meaning: "School", mnemonic: "Tree by a crossing." },
  { char: "先", romaji: "sen", meaning: "Ahead/Teacher", mnemonic: "Person walking before." },
  { char: "何", romaji: "nani", meaning: "What", mnemonic: "Person carrying something." },
  { char: "車", romaji: "kuruma", meaning: "Car", mnemonic: "A bird's eye view of a cart." },
  { char: "名", romaji: "na", meaning: "Name", mnemonic: "Mouth at night." },
  { char: "万", romaji: "man", meaning: "10,000", mnemonic: "A bird soaring (Huge number)." }
],
    n4: [],
    n3: [],
    n2: [],
    n1: []
  }
};